version: '3'

services:
  app:
    tty: true
    container_name: bbs
    build: .
    command: bundle exec rackup config.ru -p 5000 -o 0.0.0.0
    volumes:
      - .:/usr/src/bbs
    ports:
      - "5000:5000"
